# Generated by Django 2.1.8 on 2019-07-21 03:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import multitenancy.managers
import multitenancy.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultitenancyGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            bases=('auth.group', models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('site_objects', multitenancy.managers.SiteSpecificManager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)+([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$', 'Please enter a valid domain name, e.g. example.com.'), multitenancy.validators.HostnameValidator(), multitenancy.validators.AliasValidator()], verbose_name='domain name')),
                ('site_name', models.CharField(help_text='Human-readable name for the site.', max_length=255, verbose_name='site name')),
                ('preferred_domain', models.CharField(blank=True, default='', help_text="What domain name do you prefer people use for this site? <br>If set, this value must match a previously saved Site Alias. If left blank, this Site's canonical domain will be used, instead.", max_length=100, validators=[multitenancy.validators.PreferredHostnameValidator], verbose_name='Preferred Domain')),
                ('is_root_site', models.BooleanField(default=False, help_text='If true, this site will host only the admin interface for managing other sites.', verbose_name='is root site')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'db_table': 'multitenancy_site',
                'ordering': ('domain',),
            },
            managers=[
                ('objects', multitenancy.managers.SiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='SiteAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(error_messages={'unique': 'This domain name is already in use by another Site.'}, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)+([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$', 'Please enter a valid domain name, e.g. example.com.'), multitenancy.validators.HostnameValidator(), multitenancy.validators.AliasValidator()])),
            ],
            options={
                'verbose_name': 'site alias',
                'verbose_name_plural': 'site aliases',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='multitenancy.SiteAlias', verbose_name='Site Aliases'),
        ),
        migrations.AddField(
            model_name='multitenancygroup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multitenancy_multitenancygroups', related_query_name='multitenancy_multitenancygroups', to='multitenancy.Site'),
        ),
    ]
